# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNS_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNS_Practice
  
  pod 'SnapKit'
  pod 'Then'

  target 'SNS_PracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SNS_PracticeUITests' do
    # Pods for testing
  end

end
